### PR TITLE
Auxiliary data

### PR DESCRIPTION
**Pull request by gmanatole**
New class and module to join weather and environment data to an existing dataset.

NOTEBOOK TO TEST CLASS IS AVAILABLE IN '/home/datawork-osmose/osmose-datarmor/notebooks'

Multiple scenarios : 

1. **No gps data, no era data** : creates dataframe from timestamps and loads lat, lon, depth (for now 'nan' because not in metadata), shore distance and bathymetry
2. **No gps data, era data** : If era data is in .../auxiliary/weather/era/, a spatio temporal join is possible (different options : nearest point, interpolation, cube and cylinder average). Variables for join depend on variables downloaded from the climate data store (cds). Also joins lat, lon, depth, shore distance, bathymetry and wind fetch as well.
3. **gps data, no era data** : Creates dataframe based on timestamps from gps file. gps file needs to have correct columns. Joins lat, lon, depth, shore distance and bathymetry
4. **gps data, era data** : Creates full dataframe based on timestamps from gps file

### CODE REVIEW

**Comment by Rumengol** [comment]
Since it is meant to be added in the next major release of OSmOSE, the pull request should be against the develop branch rather than main.

**Comment by cazaudo** [comment]
hello githubers, 

@gmanatole your notebook really runs on env_name = "osmose" ? i guess not

@Rumengol what means "against" in your message please ? not sure i understand

**Comment by gmanatole** [comment]
@cazaudo the notebook runs on osmose_dev

**Comment by gmanatole** [comment]
That's right.

And what @Rumengol meant is that I tried merging auxiliary_branch with main which is the sable branch as of now.
I should have merged on develop and looked for conflicts with that branch as the Auxiliary class will be in version 2 that is being developed on that branch.

**Review by cazaudo — CHANGES_REQUESTED** [review]
see my last comms

**Comment by cazaudo** [comment]
need to be tested on Datarmor now

**Comment by gmanatole** [comment]
REMARQUES

1. date_template function ambiguous. Why is it used in the join_welch method but not in the __init__ method when converting time to epoch ?
2. In join_welch, interpolation is done for ttt series. Why not use self.timestamps in both cases?
3. join_era should be applied only to welch data and not self.df. If a fixed hydrophone has for instance an original dataset with wav files longer than 1h, we will lose in precision.
4. Bathymetry, shore distance and wind fetch not available to user yet.

**Comment by cazaudo** [comment]
1. it was a quick and dirty way to retrieve timestamps from npz files , you hardcoded the date template in your code which was not working ; the timestamp in filenames of welch files not the same whether you work on original or segmented files ........ a solution would be to format original filenames as segmented ones , ie with date template "%Y_%m_%dT%H_%M_%S" , to be discussed later
2. good shot , i changed it 
3.  i did not touch the join_era() method ,  but if i understand correctly join_welch should be before join_era() ? and we should use the joined df in join_era() instead of individual self.timestamps (not interpolated by join_welch, same for latitude and longitude)
4. i think there is enough for the moment, we 'll add it a bit later

**Comment by cazaudo** [comment]
got it , it works now by redefining the following at the beginning of join_era()
        self.latitude=self.df.lat
        self.longitude=self.df.lon
        self.timestamps=self.df.time
dirty but i will let it like that to make it explicit
new order of methods:
appli_weather = Auxiliary( ... )
appli_weather.join_welch()
appli_weather.join_era()
appli_weather.save_aux_data()

**Review by cazaudo — APPROVED** [review]

**Pull request merged**
